version: "3"
services:
    api-gateway:
        build:
            context: "./api-gateway/"
            dockerfile: "./Dockerfile"
        depends_on:
            - book-service
            - user-service
        # environment:
        #     - USER_SERVICE_URI=http://user-service:3100
        #     - BOOK_SERVICE_URI=http://book-service:3101
        ports:
            - "8080:8080"
        volumes:
            - ./api-gateway:/usr/src/app

    user-service:
        build:
            context: "./user-service/"
            dockerfile: "./Dockerfile"
        environment:
            - PORT=3100
        # ports:
        #     - "3100:3100"
        volumes:
            - ./user-service:/usr/src/app

    book-service:
        build:
            context: "./book-service/"
            dockerfile: "./Dockerfile"
        environment:
            - PORT=3101
        # ports:
        #     - "3101:3101"
        volumes:
            - ./book-service:/usr/src/app
